##--- Profile defaults

# non-slurm profile defaults
use-conda: True
printshellcmds: True
use-singularity: True

##--- Protein sequence, protein domains and target genomes --##
protein_table: '03_config/protein_database.tsv'
target_genomes: '03_config/target_genomes.tsv'

##--- Path To Executable And Dependencies ---#
BITACORA: "bitacora-master" #PATH to BITACORA commandline script, if error check params for rule "bitacora_full" in 02_rules/bitacora-pipeline.smk
scripts: "bitacora-master/Scripts" #Path to BITACORA Scripts directory, if error check params for rule "bitacora_full" in 02_rules/bitacora-pipeline.smk
GeMoMa: "GeMoMa-1/GeMoMa-1.9.jar" #Path to GeMoMa executable jar file, if error check params for rule "bitacora_full" in 02_rules/bitacora-pipeline.smk
tools: "bitacora-master/Scripts/Tools" #Bitacora tools
blast: "$CONDA_PREFIX/bin/" #Path to BLAST executable
hmmer: "$CONDA_PREFIX/bin/" #Path to HMMER executable

##--- setting for BITACORA ---#
use_blast: "T" #conduct BLASTP (T or F)
maxintron: 40000 #Maximum length of an intron
algorithm: "gemoma", #Algorithm used to predict novel genes. Specify 'gemoma' or 'proximity'
addition_filter: "T" #Conduct an additional filtering of the annotations if -r T. Specify 'T' or 'F' 
evalue: 1e-6 #Evalue for BLAST and HMMER
min_length: 30 #Minimum length to retain identified genes
tools: "bitacora-master/Scripts/Tools" #Bitacora tools
retain_genes: "T" #Retain all annotated genes, without any clustering of identical copies
clean_out: "T" #Clean output files

##--- conda environments --##
env-bitacora: "../01_envs/GeMoMa_v1_9.yaml"




