##--- Profile defaults

# non-slurm profile defaults
use-conda: True
printshellcmds: True

##--- Protein sequence, protein domains and target genomes --##
protein_table: 'configuration/protein_database.tsv'
target_genomes: 'configuration/target_genomes.tsv'

##--- Path To Executable And Dependencies ---##
bitacora_repo_url: "https://github.com/YourUsername/BITACORA.git"
BITACORA: "bin/bitacora" #PATH to BITACORA commandline script, if error check params for rule "bitacora_full" in 02_rules/bitacora-pipeline.smk
scripts: "bin/bitacora/Scripts" #Path to BITACORA Scripts directory, if error check params for rule "bitacora_full" in 02_rules/bitacora-pipeline.smk
GeMoMa: "$CONDA_PREFIX/bin/GeMoMa" #Path to GeMoMa executable jar file, if error check params for rule "bitacora_full" in 02_rules/bitacora-pipeline.smk
tools: "bin/bitacora/Scripts/Tools" #Bitacora tools
blast: "$CONDA_PREFIX/bin/" #Path to BLAST executable
hmmer: "$CONDA_PREFIX/bin/" #Path to HMMER executable

##--- setting for BITACORA ---##
use_blast: "T" #conduct an additional BLASTP search in addition to HMMER to validate novel genes
maxintron: 15000 #Maximum length of an intron ( needed for proximity algorithm)
evalue: 1e-5 #Evalue for BLAST and HMMER
clean_out: "T" #Clean output files
outdir: ""

##--- computational resources ---##
cpus: 48 #number of threads avaliable per bitacora run 

##--- conda environments --##
env-GeMoMA: "envs/GeMoMa.yaml"




